version: 0.2

phases:

  pre_build:
    commands:
      - IMAGE_REPO_NAME= public.ecr.aws/c7l4l0y6/tomer-ecr
      - echo "Login to ECR repository"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_NAME


  build:
    commands:
      - echo "Build docker hello-app image"
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Push docker image to ECR"
      - docker push $IMAGE_REPO_NAME:latest
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - Dockerfile
    - buildspec.yaml
