version: 0.2

phases:


  pre_build:
    commands:
      - echo "Login to ECR repository"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c7l4l0y6



  build:
    commands:
      - echo "Build docker hello-app image"
      - docker build -t tomer-ecr:latest .
      - docker tag tomer-ecr:latest tomer-ecr:$IMAGE_TAG

  post_build:
    commands:
      - echo "Push docker image to ECR"
      - docker push tomer-ecr:latest
      - docker push tomer-ecr:$IMAGE_TAG

artifacts:
  files:
    - Dockerfile
    - buildspec.yaml
